##
# Apache2 install.
#
- name: Apache | Install
  action: apt name={{ item }}
  with_items:
    - apache2
- name: Apache | Start service
  action: service name=apache2 state=started

##
# Apache2 setup.
#
- name: Apache | Enable some required modules
  action: command a2enmod rewrite vhost_alias

- name: Apache | Configuration file for our site
  action: template src=etc-apache2-sites-available-server.j2 dest=/etc/apache2/sites-available/server

- name: Apache | Disable the default site
  action: command a2dissite default

- name: Apache | Enable our new site
  action: command a2ensite server

##
# Creating Website Directory
#
- name: Apache | Create website directory
  action: file path=/home/{{ username }}/www owner={{ username }} group={{ username }} state=directory mode=0775

- name: Apache | Add basic index.html
  action: copy src=index.html dest=/home/{{ username }}/www/index.html

##
# Apache2 Restart
#
- name: Apache | Restart
  action: service name=apache2 state=restarted
