##
# Drupal Read Only module
#
- name: Drupal | Download drupal readonly module
  action: command drush --root=/home/{{ username }}/www/drupal dl -y readonlymode
  ignore_errors: True

- name: Drupal | Enable drupal readonly module
  action: command drush --root=/home/{{ username }}/www/drupal en -y readonlymode

- name: Drupal | Activate readonly module for "Read Only" module
  action: command drush --root=/home/{{ username }}/www/drupal vset site_readonly 1
