##
# Drupal Read Only module
#
- name: Drupal | Download drupal readonly module
  action: command drush dl -y --destination=/home/{{ username }}/www/drupal/sites/all/modules readonly
  ignore_errors: True

- name: Drupal | Enable drupal readonly module
  action: command cd /home/{{ username }}/www/drupal && drush en -y readonly

- name: Drupal | Activate readonly module for "Read Only" module
  action: command drush vset site_readonly 1
