# Danger: this wipes a partition
# Caution/TODO: won't work on Ubuntu
# Note: vars obtained from inventory/group/host vars
#
# Naming conventions from:
# http://www.gluster.org/community/documentation/index.php/HowTos:Brick_naming_conventions
---

- name: Check for existing partition
  stat: path={{gluster_vol_path}}
  register: stat_vol1

- name: Add XFS programs
  apt: pkg=xfsprogs state=present

- name: Make filesystem on device
  command: /sbin/mkfs -t {{gluster_fs_type}} -i size=512 {{gluster_raw_device}}
  when: stat_vol1.stat.exists == false
 
- name: Make top dir
  file: path={{gluster_vol_path}} state=directory owner=root group=root mode=0700
  when: stat_vol1.stat.exists == false

- name: Mount filesystem
  mount: fstype={{gluster_fs_type}} name={{gluster_vol_path}} src={{gluster_raw_device}} state=mounted
  when: stat_vol1.stat.exists == false

- name: Make brick dir in filesystem
  file: path={{gluster_vol_path}}/brick state=directory owner=root group=root mode=0700
  when: stat_vol1.stat.exists == false
