##
# PHP5 install.
#
- name: PHP5 | Install
  action: apt name={{ item }}
  with_items:
    - php5
    - php5-mysql
    - php5-curl
    - php5-gd
    - php5-mbstring
    - libapache2-mod-php5
- name: PHP | Configuration of php.ini
  action: template src=etc-php5-apache2-php-ini.j2 dest=/etc/php5/apache2/php.ini
  notify:
    - start apache2  ## or - start nginx
- name: PHP5 | Add info.php to the server's virtual host
  action: copy src=info.php dest=/home/{{ username }}/www/info.php
