# ansible-playbook create-gluster.yml -v -i hosts/dev --private-key=~/AeroFS/AWS-keys/chriskoansys.pem 

- name: Create Gluster
  hosts: gluster-bricks
  sudo: yes
  # vars:
  #   # should have redhat and size stuff here? or in group/host files?
  #   foo: bar
  roles:
    - gluster-brick
  tasks:
    - name: Calling the brick creator...
      debug: msg="Calling the brick creator..."

