- hosts: webservers
  user: ubuntu
  sudo: yes

  vars:
    username: ubuntu
    drupal_path: '/home/{{ username }}/www/drupal'

  roles:
    - ubuntu
    - apache2
    - mysql
    - php5
    - drupal-install
